### ISSUE TITLE
请问论文中使用的测试集生成的对抗样本可以公开吗？

### ISSUE THREAD

**Issue by NTDXYG** [Zhangxq-1/ACCENT-repository#1]
作者您好，看了您论文之后，恰好我也是用的PCSD和JCSD两个数据集，baseline中也包含了rencos，我想获得您论文中rencos模型使用的对抗样本和对应的生成注释数据吗？我也想比较下我提出的模型的鲁棒性，麻烦了，谢谢

**Comment by Zhangxq-1** [comment]
您好，目前论文正在审稿阶段，后续会公开，谢谢！

**Comment by NTDXYG** [comment]
好的👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月8日(周日) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zhangxq-1/ACCENT-repository] 请问论文中使用的测试集生成的对抗样本可以公开吗？ (#1)




 
您好，目前论文正在审稿阶段，后续会公开，谢谢！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NTDXYG** [comment]
您好，祝贺您的论文被TOSEM录用。我是强烈地希望您能公开在Java和python这两个语料库的测试集上生成的对抗样本，对于您使用mask来做对抗训练我也是非常感兴趣，这让我觉得和对比学习中使用两次dropout生成正例有类似的作用。

**Comment by Zhangxq-1** [comment]
可以



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月15日 20:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Zhangxq-1/ACCENT-repository] 请问论文中使用的测试集生成的对抗样本可以公开吗？ (#1) |

您好，祝贺您的论文被TOSEM录用。我是强烈地希望您能公开在Java和python这两个语料库的测试集上生成的对抗样本，对于您使用mask来做对抗训练我也是非常感兴趣，这让我觉得和对比学习中使用两次dropout生成正例有类似的作用。

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NTDXYG** [comment]
感谢，这是我qq744621980，希望跟您一起学习交流



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月15日(周一) 晚上8:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zhangxq-1/ACCENT-repository] 请问论文中使用的测试集生成的对抗样本可以公开吗？ (#1)




 可以
 
 
 
 发自 网易邮箱大师
 
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2021年11月15日 20:11 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;、State ***@***.***&gt; |
 | 主题 | Re: [Zhangxq-1/ACCENT-repository] 请问论文中使用的测试集生成的对抗样本可以公开吗？ (#1) |
 
 您好，祝贺您的论文被TOSEM录用。我是强烈地希望您能公开在Java和python这两个语料库的测试集上生成的对抗样本，对于您使用mask来做对抗训练我也是非常感兴趣，这让我觉得和对比学习中使用两次dropout生成正例有类似的作用。
 
 —
 You are receiving this because you modified the open/close state.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
